/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../../packages/sanity-types/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteUrl?: string;
  titleTemplate?: string;
  defaultDescription?: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  locale?: string;
  twitterHandle?: string;
  robotsDefault?: {
    noIndex?: boolean;
    noFollow?: boolean;
  };
  socialMedia?: Array<{
    platform?: "instagram" | "x" | "linkedin";
    url?: string;
    _key: string;
  }>;
  footerCopyright?: string;
  footerCTA?: LinkComponent;
  footerLinks?: Array<{
    title?: string;
    cta?: LinkComponent;
    _key: string;
  }>;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type LinkComponent = {
  _type: "linkComponent";
  text?: string;
  linkType?: "internal" | "external" | "custom";
  internalLink?: PageReference | PostReference;
  externalUrl?: string;
  customLink?: string;
  openInNewTab?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  cta?: LinkComponent;
  navItems?: Array<{
    label?: string;
    subtitle?: string;
    linkType?: "internal" | "external";
    internalLink?: PageReference;
    externalUrl?: string;
    openInNewTab?: boolean;
    children?: Array<{
      label?: string;
      subtitle?: string;
      linkType?: "internal" | "external";
      internalLink?: PageReference;
      externalUrl?: string;
      openInNewTab?: boolean;
      _type: "childNavItem";
      _key: string;
    }>;
    _type: "navItem";
    _key: string;
  }>;
};

export type Redirects = {
  _id: string;
  _type: "redirects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  redirects?: Array<{
    source?: string;
    destination?: string;
    isPermanent?: boolean;
    _type: "redirect";
    _key: string;
  }>;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  twitterTitle?: string;
  twitterDescription?: string;
  twitterImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
};

export type ImageComponent = {
  _type: "imageComponent";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type HeadingComponent = {
  _type: "headingComponent";
  title?: string;
  tag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
};

export type CtaSection = {
  _type: "ctaSection";
  heading?: HeadingComponent;
  image?: ImageComponent;
  cta?: LinkComponent;
};

export type HeroSection = {
  _type: "heroSection";
  heading?: HeadingComponent;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  featuredImage?: ImageComponent;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageComponent)
  >;
  publishedAt?: string;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  parent?: PageReference;
  builder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & CtaSection)
  >;
  seo?: Seo;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  builder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & CtaSection)
  >;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SiteSettings
  | PageReference
  | PostReference
  | LinkComponent
  | SanityImageCrop
  | SanityImageHotspot
  | Navigation
  | Redirects
  | Seo
  | ImageComponent
  | HeadingComponent
  | CtaSection
  | HeroSection
  | Post
  | Slug
  | Page
  | Home
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/queries/globals.ts
// Variable: NAVIGATION
// Query: *[_type == "navigation"][0] {  cta {    text,linkType,openInNewTab,"href": select(  linkType == "internal" => internalLink->slug.current,  linkType == "external" => externalUrl,  linkType == "custom" => customLink,  "#")  },  navItems[] {    label,    "href": select(      linkType == "internal" => internalLink->slug.current,      linkType == "external" => externalUrl,      "#"    ),    linkType,    openInNewTab,    children[] {      label,      "href": select(        linkType == "internal" => internalLink->slug.current,        linkType == "external" => externalUrl,        "#"      ),      linkType,      openInNewTab    }  }}
export type NAVIGATION_RESULT = {
  cta: {
    text: string | null;
    linkType: "custom" | "external" | "internal" | null;
    openInNewTab: boolean | null;
    href: string | "#" | null;
  } | null;
  navItems: Array<{
    label: string | null;
    href: string | "#" | null;
    linkType: "external" | "internal" | null;
    openInNewTab: boolean | null;
    children: Array<{
      label: string | null;
      href: string | "#" | null;
      linkType: "external" | "internal" | null;
      openInNewTab: boolean | null;
    }> | null;
  }> | null;
} | null;

// Source: ../web/src/queries/globals.ts
// Variable: REDIRECTS
// Query: *[_type == "redirects"][0] {    redirects[] {      source,      destination,      isPermanent    }  }
export type REDIRECTS_RESULT = {
  redirects: Array<{
    source: string | null;
    destination: string | null;
    isPermanent: boolean | null;
  }> | null;
} | null;

// Source: ../web/src/queries/globals.ts
// Variable: SITE_SETTINGS
// Query: *[_type == "siteSettings"][0] {    siteName,    siteUrl,    titleTemplate,    defaultDescription,    "defaultOgImage": defaultOgImage.asset->url,    locale,    twitterHandle,    "noIndex": coalesce(robotsDefault.noIndex, false),    "noFollow": coalesce(robotsDefault.noFollow, false),    footerCopyright,    socialMedia,    footerLinks[] {      title,      cta { text,linkType,openInNewTab,"href": select(  linkType == "internal" => internalLink->slug.current,  linkType == "external" => externalUrl,  linkType == "custom" => customLink,  "#") }    },    footerCTA {      text,linkType,openInNewTab,"href": select(  linkType == "internal" => internalLink->slug.current,  linkType == "external" => externalUrl,  linkType == "custom" => customLink,  "#")    }  }
export type SITE_SETTINGS_RESULT = {
  siteName: string | null;
  siteUrl: string | null;
  titleTemplate: string | null;
  defaultDescription: string | null;
  defaultOgImage: string | null;
  locale: string | null;
  twitterHandle: string | null;
  noIndex: boolean | false;
  noFollow: boolean | false;
  footerCopyright: string | null;
  socialMedia: Array<{
    platform?: "instagram" | "linkedin" | "x";
    url?: string;
    _key: string;
  }> | null;
  footerLinks: Array<{
    title: string | null;
    cta: {
      text: string | null;
      linkType: "custom" | "external" | "internal" | null;
      openInNewTab: boolean | null;
      href: string | "#" | null;
    } | null;
  }> | null;
  footerCTA: {
    text: string | null;
    linkType: "custom" | "external" | "internal" | null;
    openInNewTab: boolean | null;
    href: string | "#" | null;
  } | null;
} | null;

// Source: ../web/src/queries/pages.ts
// Variable: HOME_PAGE
// Query: *[_type == "home" && _id == "home"][0] {  title,  seo,  builder[] {  _type,  _type == "heroSection" => {  heading {    title,    tag  },  body},  _type == "ctaSection" => {  heading {    title,    tag  },  image {    asset->{  url,  metadata {    dimensions {      width,      height    }  }},    alt  },  cta {    text,linkType,openInNewTab,"href": select(  linkType == "internal" => internalLink->slug.current,  linkType == "external" => externalUrl,  linkType == "custom" => customLink,  "#")  }}}}
export type HOME_PAGE_RESULT = {
  title: string | null;
  seo: Seo | null;
  builder: Array<
    | {
        _type: "ctaSection";
        heading: {
          title: string | null;
          tag: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | null;
        } | null;
        image: {
          asset: {
            url: string | null;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          alt: string | null;
        } | null;
        cta: {
          text: string | null;
          linkType: "custom" | "external" | "internal" | null;
          openInNewTab: boolean | null;
          href: string | "#" | null;
        } | null;
      }
    | {
        _type: "heroSection";
        heading: {
          title: string | null;
          tag: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | null;
        } | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
      }
  > | null;
} | null;

// Source: ../web/src/queries/pages.ts
// Variable: ALL_PAGES
// Query: *[_type == "page"] {  title,  "slug": select(    defined(parent) => parent->slug.current + "/" + slug.current,    slug.current  )}
export type ALL_PAGES_RESULT = Array<{
  title: string | null;
  slug: string | null;
}>;

// Source: ../web/src/queries/pages.ts
// Variable: PAGE_BY_SLUG
// Query: *[_type == "page" && (    (!defined(parent) && slug.current == $slug) ||    (defined(parent) && parent->slug.current + "/" + slug.current == $slug)  )][0] {    title,    "slug": select(      defined(parent) => parent->slug.current + "/" + slug.current,      slug.current    ),    seo,    builder[] {  _type,  _type == "heroSection" => {  heading {    title,    tag  },  body},  _type == "ctaSection" => {  heading {    title,    tag  },  image {    asset->{  url,  metadata {    dimensions {      width,      height    }  }},    alt  },  cta {    text,linkType,openInNewTab,"href": select(  linkType == "internal" => internalLink->slug.current,  linkType == "external" => externalUrl,  linkType == "custom" => customLink,  "#")  }}}  }
export type PAGE_BY_SLUG_RESULT = {
  title: string | null;
  slug: string | null;
  seo: Seo | null;
  builder: Array<
    | {
        _type: "ctaSection";
        heading: {
          title: string | null;
          tag: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | null;
        } | null;
        image: {
          asset: {
            url: string | null;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          alt: string | null;
        } | null;
        cta: {
          text: string | null;
          linkType: "custom" | "external" | "internal" | null;
          openInNewTab: boolean | null;
          href: string | "#" | null;
        } | null;
      }
    | {
        _type: "heroSection";
        heading: {
          title: string | null;
          tag: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | null;
        } | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
      }
  > | null;
} | null;

// Source: ../web/src/queries/posts.ts
// Variable: ALL_POSTS
// Query: *[_type == "post"] | order(publishedAt desc) {  _id,  title,  "slug": slug.current,  publishedAt,  featuredImage {    asset->{  url,  metadata {    dimensions {      width,      height    }  }},    alt  }}
export type ALL_POSTS_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  featuredImage: {
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
}>;

// Source: ../web/src/queries/posts.ts
// Variable: POST_BY_SLUG
// Query: *[_type == "post" && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  publishedAt,  seo,  featuredImage {    asset->{  url,  metadata {    dimensions {      width,      height    }  }},    alt  },  body}
export type POST_BY_SLUG_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  seo: Seo | null;
  featuredImage: {
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  body: Array<
    | ({
        _key: string;
      } & ImageComponent)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "navigation"][0] {\n  cta {\n    \ntext,\nlinkType,\nopenInNewTab,\n"href": select(\n  linkType == "internal" => internalLink->slug.current,\n  linkType == "external" => externalUrl,\n  linkType == "custom" => customLink,\n  "#"\n)\n\n  },\n  navItems[] {\n    label,\n    "href": select(\n      linkType == "internal" => internalLink->slug.current,\n      linkType == "external" => externalUrl,\n      "#"\n    ),\n    linkType,\n    openInNewTab,\n    children[] {\n      label,\n      "href": select(\n        linkType == "internal" => internalLink->slug.current,\n        linkType == "external" => externalUrl,\n        "#"\n      ),\n      linkType,\n      openInNewTab\n    }\n  }\n}': NAVIGATION_RESULT;
    '\n  *[_type == "redirects"][0] {\n    redirects[] {\n      source,\n      destination,\n      isPermanent\n    }\n  }\n': REDIRECTS_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    siteName,\n    siteUrl,\n    titleTemplate,\n    defaultDescription,\n    "defaultOgImage": defaultOgImage.asset->url,\n    locale,\n    twitterHandle,\n    "noIndex": coalesce(robotsDefault.noIndex, false),\n    "noFollow": coalesce(robotsDefault.noFollow, false),\n    footerCopyright,\n    socialMedia,\n    footerLinks[] {\n      title,\n      cta { \ntext,\nlinkType,\nopenInNewTab,\n"href": select(\n  linkType == "internal" => internalLink->slug.current,\n  linkType == "external" => externalUrl,\n  linkType == "custom" => customLink,\n  "#"\n)\n }\n    },\n    footerCTA {\n      \ntext,\nlinkType,\nopenInNewTab,\n"href": select(\n  linkType == "internal" => internalLink->slug.current,\n  linkType == "external" => externalUrl,\n  linkType == "custom" => customLink,\n  "#"\n)\n\n    }\n  }\n': SITE_SETTINGS_RESULT;
    '*[_type == "home" && _id == "home"][0] {\n  title,\n  seo,\n  \nbuilder[] {\n  _type,\n  \n_type == "heroSection" => {\n  heading {\n    title,\n    tag\n  },\n  body\n},\n  \n_type == "ctaSection" => {\n  heading {\n    title,\n    tag\n  },\n  image {\n    \nasset->{\n  url,\n  metadata {\n    dimensions {\n      width,\n      height\n    }\n  }\n},\n    alt\n  },\n  cta {\n    \ntext,\nlinkType,\nopenInNewTab,\n"href": select(\n  linkType == "internal" => internalLink->slug.current,\n  linkType == "external" => externalUrl,\n  linkType == "custom" => customLink,\n  "#"\n)\n\n  }\n}\n}\n}': HOME_PAGE_RESULT;
    '*[_type == "page"] {\n  title,\n  "slug": select(\n    defined(parent) => parent->slug.current + "/" + slug.current,\n    slug.current\n  )\n}': ALL_PAGES_RESULT;
    '\n  *[_type == "page" && (\n    (!defined(parent) && slug.current == $slug) ||\n    (defined(parent) && parent->slug.current + "/" + slug.current == $slug)\n  )][0] {\n    title,\n    "slug": select(\n      defined(parent) => parent->slug.current + "/" + slug.current,\n      slug.current\n    ),\n    seo,\n    \nbuilder[] {\n  _type,\n  \n_type == "heroSection" => {\n  heading {\n    title,\n    tag\n  },\n  body\n},\n  \n_type == "ctaSection" => {\n  heading {\n    title,\n    tag\n  },\n  image {\n    \nasset->{\n  url,\n  metadata {\n    dimensions {\n      width,\n      height\n    }\n  }\n},\n    alt\n  },\n  cta {\n    \ntext,\nlinkType,\nopenInNewTab,\n"href": select(\n  linkType == "internal" => internalLink->slug.current,\n  linkType == "external" => externalUrl,\n  linkType == "custom" => customLink,\n  "#"\n)\n\n  }\n}\n}\n  }\n': PAGE_BY_SLUG_RESULT;
    '*[_type == "post"] | order(publishedAt desc) {\n  _id,\n  title,\n  "slug": slug.current,\n  publishedAt,\n  featuredImage {\n    \nasset->{\n  url,\n  metadata {\n    dimensions {\n      width,\n      height\n    }\n  }\n},\n    alt\n  }\n}': ALL_POSTS_RESULT;
    '*[_type == "post" && slug.current == $slug][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  publishedAt,\n  seo,\n  featuredImage {\n    \nasset->{\n  url,\n  metadata {\n    dimensions {\n      width,\n      height\n    }\n  }\n},\n    alt\n  },\n  body\n}': POST_BY_SLUG_RESULT;
  }
}
